### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore-python-client#20]
Minor. This entry appears twice
![image](https://user-images.githubusercontent.com/33161876/107664172-6d4e4780-6c8c-11eb-9dd2-d75fd349aa54.png)

**Comment by pcrespov** [comment]
New doc solves the issue. SEE https://itisfoundation.github.io/osparc-simcore-python-client/#/
<img width="454" alt="image" src="https://user-images.githubusercontent.com/32402063/196701648-db9fa328-fefd-41e1-8f34-4b195408875e.png">
